### ISSUE TITLE
Handle multiple directories synchronization

### ISSUE THREAD

**Issue by bigfoot90** [mickaelperrin/docker-unison-unox#6]
I need to synchronize two different directories on the same container.

Currently in my `docker-compose.yml` I have:
```
services:
  code:
    volumes:
      - ./code/silex:/var/www/html
      - ~/.composer:/home/.composer
```

I there away to do it without launching two unison containers and two commands on the host?
Thanks in advance.
